package nurse_db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import nurse_db.BedInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BED_INFO".
*/
public class BedInfoDao extends AbstractDao<BedInfo, String> {

    public static final String TABLENAME = "BED_INFO";

    /**
     * Properties of entity BedInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Bed_id = new Property(0, String.class, "bed_id", true, "BED_ID");
        public final static Property House_id = new Property(1, String.class, "house_id", false, "HOUSE_ID");
        public final static Property Patient_id = new Property(2, String.class, "patient_id", false, "PATIENT_ID");
        public final static Property Bed_state = new Property(3, String.class, "bed_state", false, "BED_STATE");
    };

    private DaoSession daoSession;


    public BedInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BedInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BED_INFO\" (" + //
                "\"BED_ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: bed_id
                "\"HOUSE_ID\" TEXT NOT NULL ," + // 1: house_id
                "\"PATIENT_ID\" TEXT NOT NULL ," + // 2: patient_id
                "\"BED_STATE\" TEXT NOT NULL );"); // 3: bed_state
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BED_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BedInfo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getBed_id());
        stmt.bindString(2, entity.getHouse_id());
        stmt.bindString(3, entity.getPatient_id());
        stmt.bindString(4, entity.getBed_state());
    }

    @Override
    protected void attachEntity(BedInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BedInfo readEntity(Cursor cursor, int offset) {
        BedInfo entity = new BedInfo( //
            cursor.getString(offset + 0), // bed_id
            cursor.getString(offset + 1), // house_id
            cursor.getString(offset + 2), // patient_id
            cursor.getString(offset + 3) // bed_state
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BedInfo entity, int offset) {
        entity.setBed_id(cursor.getString(offset + 0));
        entity.setHouse_id(cursor.getString(offset + 1));
        entity.setPatient_id(cursor.getString(offset + 2));
        entity.setBed_state(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(BedInfo entity, long rowId) {
        return entity.getBed_id();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(BedInfo entity) {
        if(entity != null) {
            return entity.getBed_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPatientInfoDao().getAllColumns());
            builder.append(" FROM BED_INFO T");
            builder.append(" LEFT JOIN PATIENT_INFO T0 ON T.\"PATIENT_ID\"=T0.\"PATIENT_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BedInfo loadCurrentDeep(Cursor cursor, boolean lock) {
        BedInfo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PatientInfo patientInfo = loadCurrentOther(daoSession.getPatientInfoDao(), cursor, offset);
         if(patientInfo != null) {
            entity.setPatientInfo(patientInfo);
        }

        return entity;    
    }

    public BedInfo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BedInfo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BedInfo> list = new ArrayList<BedInfo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BedInfo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BedInfo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
